# Generated by Django 5.1.4 on 2024-12-16 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_updated_date_alter_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
